spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect # 혹은 최신 버전 반영
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  devtools:
    restart:
      enabled: false

  profiles:
    active: local

  deploy:
    secret: ${DEPLOY_SECRET:local_temporary_secret_key_1234}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity-in-milliseconds: ${JWT_REFRESH_TOKEN_TIME}

kakao:
  client-id: ${bcb235643a01538feaac40d0f2c53f4b}
  client-secret: ${KAKAO_CLIENT_SECRET:} # 있으면 사용, 없으면 빈값